# Generated by Django 3.0 on 2021-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problemId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
