# Generated by Django 3.0 on 2021-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210921_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedProblem',
            fields=[
                ('problemId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
